import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { ExternalLink } from "lucide-react"

const projectsData = [
  {
    id: "cortex",
    title: "Cortex",
    url: "https://devpost.com/software/claude-cortex",
    gradientFrom: "from-blue-600",
    gradientTo: "to-purple-600",
    badge: "Anthropic Hackathon Winner",
    badgeColor: "bg-yellow-500 text-black",
    description: "A secure multi-agent reasoning and action engine. Cortex launches multiple task-based agents in parallel dynamically generated by a master planning agent.",
    tags: [ "Claude + AWS Bedrock", "Nextjs", "FastAPI", "Pydantic"]
  },
  {
    id: "intervene",
    title: "Intervene",
    url: "https://intervene-smoky.vercel.app",
    gradientFrom: "from-purple-600",
    gradientTo: "to-pink-600",
    badge: "8VC Hackathon Winner",
    badgeColor: "bg-yellow-500 text-black",
    description: "OS level AI agent that takes over and completes tasks for you. Tell Intervene what to do, and it will do it for you, autonomously in the background.",
    tags: ["Langchain", "Swift for MacOS", "FastAPI", "Llama + Llava"]
  },
  {
    id: "ideavine",
    title: "IdeaVine",
    url: "https://useideavine.com",
    gradientFrom: "from-green-600",
    gradientTo: "to-blue-600",
    badge: "1000+ Active Users",
    badgeColor: "bg-yellow-500 text-black",
    description: "Multi-modal mindmapping tool designed to help you think freely. Let AI think with you, not for you.",
    tags: ["MongoDB", "Nextjs", "Whisper", "Socket.io", "OpenAI", "Redis"]
  },
  {
    id: "hera",
    title: "Hera",
    url: "https://heradashboard.vercel.app",
    gradientFrom: "from-red-600",
    gradientTo: "to-orange-600",
    badge: "Used by the Indian Government",
    badgeColor: "bg-yellow-500 text-black",
    description: "Air Pollution analytics tool that provides the best solution to the air pollution at the neighborhood level to policymakers.",
    tags: ["PostgreSQL", "Python", "React", "Kriging", "Data Augmentation"]
  },
  {
    id: "tone",
    title: "Tone",
    url: "https://tone.computer",
    gradientFrom: "from-teal-600",
    gradientTo: "to-green-600",
    badge: "384K+ Views on X",
    badgeColor: "bg-yellow-500 text-black",
    description: "Wear your wisdom. Tone captures your lived experiences, your conversations, your ideas, your to-dos, automatically.",
    tags: ["SwiftUI", "Xcode", "Pinecone", "Supabase", "Structured Memory"]
  },
  {
    id: "ailytics",
    title: "AIlytics",
    url: "https://github.com/shubhayan935/AIlytics",
    gradientFrom: "from-indigo-600",
    gradientTo: "to-purple-600",
    badge: "Enterprise Pilot Users",
    badgeColor: null,
    description: "AI data scientist that connects directly to your databases and derives insights and visualizations through simple natural language prompts.",
    tags: ["Apache Spark", "Neo4j", "Langchain", "Reinforcement Learning", "Docker"]
  }
]

export default function Projects() {
  return (
    <section className="mb-16">
      <h2 className="text-2xl font-normal mb-8 font-garnett">Cool Stuff I've Built</h2>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {projectsData.map((project) => (
          <a key={project.id} href={project.url} target="_blank" rel="noopener noreferrer">
            <Card className="h-full bg-[#0b0c0f] border-white/10 overflow-hidden hover:bg-[#0e1015] hover:border-white/30 hover:shadow-[0_0_20px_rgba(255,255,255,0.1)] transition-all duration-300 cursor-pointer group gap-0">
              {/* Media */}
              <div className={`aspect-video bg-gradient-to-br ${project.gradientFrom} ${project.gradientTo}`} />
              
              {/* Body */}
              <CardContent className="p-6 flex flex-col h-full">
                {/* Title row with external link icon */}
                <div className="flex items-start justify-between mb-3">
                  <h3 className="text-xl font-normal text-white font-garnett">{project.title}</h3>
                  <ExternalLink className="size-4 text-white/70 group-hover:text-white transition-colors" />
                </div>

                {/* Badge */}
                {project.badge && (
                  <div className="mb-4">
                    <Badge className="text-[13px] font-medium rounded-md px-2 py-1 bg-white/15">{project.badge}</Badge>
                  </div>
                )}

                {/* Description */}
                <p className="text-gray-300 mb-6 flex-grow leading-relaxed">
                  {project.description}
                </p>

                {/* Tags */}
                <div className="flex flex-wrap gap-2 mt-auto">
                  {project.tags.map((tag) => (
                    <span key={tag} className="text-xs px-3 py-1 rounded-full bg-white/5 border border-white/10 text-gray-300">
                      {tag}
                    </span>
                  ))}
                </div>
              </CardContent>
            </Card>
          </a>
        ))}
      </div>
    </section>
  )
}